### ISSUE TITLE
Error When Using Component Decorator

### ISSUE THREAD

**Issue by szammyboi** [lume/classy-solid#1]
I have a solid-js project setup with their basic Vite template. I enabled experimental decorators with babel and was able to successfully use the @reactive decorator. However, whenever I try to use the @component decorator I get the following error:

`A class descriptor's .kind property must be "class", but a decorator created a class descriptor with .kind "undefined"`

I was able to solve the problem by exporting the class and wrapping it inside the component function like such:

`export default component(Home)`
Home being the class name

**Comment by trusktr** [comment]
Hello, sorry for the late reply, I was unsubscribed to my own repo xD. What version of decorators are you using? I perhaps need to update to the latest spec that Babel supports (which is now itself outdated too I think).

**Comment by trusktr** [comment]
After testing, it looks like this error happens with decorator mode `2018-09`.

Reproduction in [Babel repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBKC2AHcBTMsC8MAUBhANgIYQQCUMGAfDAN4BQMMATilAK5NgwBmbYwUAJbgciJiERlaDRjAD0cmADoVMgL50NdUJFgtCAwQDcUFHAWJSq0xi3acYFkprraiJGACFiKJxGlaAAIIyGBoUHSB-oYmbpYwALIAnn4wKAAeUGgAJv7eEL7u_vSaQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Cstage-0&prettier=true&targets=&version=7.18.5&externalPlugins=&assumptions=%7B%7D)

For now just use `legacy` mode. I need to add more tests to handle each mode.

The difficult thing for decorator developers currently (until the decorator spec finally lands and is implemented in JS runtimes) is that there are many permutations of compiler configurations to test in order not to fail in some cases:

1. TypeScript with `useDefineForClassFields: true`
2. TypeScript with `useDefineForClassFields: false`
3. Babel with class-properties "loose:true" and decorator mode "legacy"
4. Babel with class-properties "loose:true" and decorator mode "2018-09"
5. Babel with class-properties "loose:true" and decorator mode "2021-12"
6. Babel with class-properties "loose:false" and decorator mode "legacy"
7. Babel with class-properties "loose:false" and decorator mode "2018-09"
8. Babel with class-properties "loose:false" and decorator mode "2021-12"

We have to run tests 8 times, each time with a different build configuration, to ensure it works in all. And that didn't include other build tools. I might need to add tests for [esbuild decorators](https://www.npmjs.com/package/@anatine/esbuild-decorators) for example.

Quite a mess for decorator authors currently, but when they finally arrive natively, it will be pretty awesome.

**Comment by trusktr** [comment]
Almost done updating classy-solid to stage 3 decorators ( https://github.com/lume/classy-solid/pull/4 ). Legacy modes will no longer be supported, and their implementation removed. 🎉  Release coming soon.
