### ISSUE TITLE
Document steps needed to use decorators with vite

### ISSUE THREAD

**Issue by GodBleak** [lume/classy-solid#2]
I think many use Vite with Solid, but I noticed there aren't any instructions on using classy-solid with Vite. Using the example car class from the readme will cause errors with Vite if it's not configured to use decorators (`Support for the experimental syntax 'decorators' isn't currently enabled`).

To do so, one can install `@babel/plugin-proposal-class-properties`, and `@babel/plugin-proposal-decorators`. Then update their `vite.config.ts` file to include: 
```ts
// ...
solidPlugin({
     babel: {
          plugins: [
               ["@babel/plugin-proposal-decorators", { legacy: true }],
               "@babel/plugin-proposal-class-properties",
          ]
     },
}),
// ...
```
I think it would be beneficial to add this or similar instructions to the readme.

**Comment by trusktr** [comment]
Nice, thanks, may as well copy this to the README

**Comment by trusktr** [comment]
Nice, thanks, may as well copy this to the README
