### ISSUE TITLE
TypeScript does support stage 3 decorators!

### ISSUE THREAD

**Issue by petermakeswebsites** [lume/classy-solid#7]
I had an idea to implement something like classy-solid does because one of the qualms I have with Solid is its unnecessary verbosity, which decorators would definitely help with. I also find class-based components to be a better fit generally because to me classes and mutability go hand-in-hand and often times component has mutating data - especially when signals are involved.

Anyway, [stage 3 decorators are available in TS 5](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators). I haven't really taken a look into your source code yet, just saw the readme and read that TS doesn't support them. I assume there's some stuff worth updating.

**Comment by trusktr** [comment]
Hey, thanks for writing! We have in fact since updated to Stage 3 decorators, and dropped legacy decorator support (too much work to maintain legacy alongside the new format, making the code messier).

Can't wait for decorators to land in a JS engines!
